marimon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        '',
        LoginView.as_view(template_name='registration/login.html'),
        name='login'
    ),
    path('logout/', LogoutView.as_view(), name='logout'),
    path(
        'point_of_sale/',
        include('point_of_sale.urls', namespace='point_of_sale')
    )
]

point_of_sale/urls.py
from django.urls import path
from . import views

app_name = 'point_of_sale'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'sale/<int:sale_id>/',
        views.sale_detail,
        name='sale_detail'
    ),
    path(
        'categories/',
        views.categories,
        name='categories'
    ),
    path(
        'category/<int:category_id>/products/',
        views.products_by_category,
        name='products_by_category'
    ),
    path(
        'products/',
        views.products,
        name='products'
    ),
    path(
        'product/<int:product_id>/',
        views.product_detail,
        name='product_detail'
    ),
    path(
        'new-sale/',
        views.new_sale,
        name='new_sale'
    ),
    path(
        'get-product/<int:product_id>',
        views.get_product,
        name='get_product'
    ),
    path(
        'get_product_suggestions/',
        views.get_product_suggestions,
        name='get_product_suggestions'
    ),
    path(
        'campaigns/',
        views.campaigns,
        name='campaigns'
    ),
    path(
        'campaign/<int:campaign_id>',
        views.campaign_detail,
        name='campaign_detail'
    ),
    path(
        'end_campaign/<int:campaign_id>',
        views.end_campaign,
        name='end_campaign'
    ),
    path(
        'get_client_email_suggestions/',
        views.get_client_email_suggestions,
        name='get_client_email_suggestions'
    ),
]

point_of_sale/models.py
import threading
from io import BytesIO
from time import sleep

from PIL import Image
from django.db import models
import base64

from .constants import DEFAULT_PRODUCT_IMAGE, SIZE_CHOICES, COLOR_CHOICES
from .mailers import NewCampaignMailer


class Category(models.Model):
    """
        Model representing a product category.
        Each category can be associated with multiple products, forming a one-to-many relationship.
    """
    name = models.CharField(max_length=100, help_text="Nombre de la categoría")
    is_active = models.BooleanField(
        default=True, help_text="Indica si la categoría está activa o no"
    )
    created_at = models.DateTimeField(
        auto_now_add=True, help_text="Fecha de creación de la categoría"
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        help_text="Fecha de la última actualización de la categoría"
    )

    def __str__(self):
        return self.name


class Product(models.Model):
    """
        Model representing a product category.
        Each product belongs to a specific category, forming a many-to-one relationship.
        Each product can be associated with multiple sales, forming a one-to-many relationship.
    """
    name = models.CharField(max_length=100, help_text="Nombre del producto")
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE,
        help_text="Categoría a la que pertenece el producto"
    )
    inventory_quantity = models.IntegerField(
        default=0, help_text="Cantidad en inventario del producto"
    )
    buy_price = models.DecimalField(
        max_digits=8, decimal_places=2,
        help_text="Precio de compra del producto"
    )
    sold_price = models.DecimalField(
        max_digits=8, decimal_places=2,
        help_text="Precio de venta del producto"
    )
    image = models.ImageField(
        upload_to='product_images', null=True, blank=True,
        help_text="Imagen del producto"
    )
    size = models.CharField(
        max_length=2, choices=SIZE_CHOICES,
        help_text="Talla del producto", default=None
    )
    color = models.CharField(
        max_length=50, choices=COLOR_CHOICES,
        help_text="Color del producto", default=None
    )
    is_active = models.BooleanField(
        default=True, help_text="Indica si el producto está activo o no"
    )
    created_at = models.DateTimeField(
        auto_now_add=True, help_text="Fecha de creación del producto"
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        help_text="Fecha de la última actualización del producto"
    )

    def __str__(self):
        return f"{self.name}/{self.color}/{self.size}"

    def to_dict(self):
        data = {
            "id": self.id,
            "name": self.name,
            "category": self.category.name,
            "inventory_quantity": self.inventory_quantity,
            "buy_price": self.buy_price,
            "sold_price": self.sold_price,
            "is_active": self.is_active,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "size": self.size,
            "color": self.color,
        }

        url = self.image if self.image else DEFAULT_PRODUCT_IMAGE

        with BytesIO() as buffer:
            image = Image.open(url)
            # Convierte la imagen a modo RGB
            image = image.convert("RGB")
            image.save(buffer, format="JPEG")
            data["image"] = base64.b64encode(buffer.getvalue()).decode()

        return data

    def get_image_as_base64(self):
        url = self.image if self.image else DEFAULT_PRODUCT_IMAGE

        with BytesIO() as buffer:
            image = Image.open(url)
            # Convierte la imagen a modo RGB
            image = image.convert("RGB")
            image.save(buffer, format="JPEG")
            return base64.b64encode(buffer.getvalue()).decode()

    @classmethod
    def get_product_by_id(cls, product_id):
        return cls.objects.get(id=product_id)


class Campaign(models.Model):
    name = models.CharField(max_length=100, help_text="Nombre de la campaña")
    place = models.CharField(max_length=100, help_text="Lugar de la campaña")
    address = models.CharField(
        max_length=100,
        help_text="Dirección de la campaña"
    )
    image = models.ImageField(
        upload_to='campaign_images', null=True, blank=True,
        help_text="Imagen de la campaña"
    )
    start_date = models.DateTimeField(
        help_text="Fecha de inicio de la campaña"
    )
    end_date = models.DateTimeField(
        help_text="Fecha de fin de la campaña"
    )
    cover = models.DecimalField(
        default=0, max_digits=8, decimal_places=2,
        help_text="Cuota de entrada al bazar"
    )
    is_active = models.BooleanField(
        default=True,
        help_text="Indica si la campaña está activa o no"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Fecha de creación de la campaña"
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        help_text="Fecha de la última actualización de la campaña"
    )

    def __str__(self):
        return self.name

    def to_dict(self):
        data = {
            "id": self.id,
            "name": self.name,
            "place": self.place,
            "address": self.address,
            "start_date": self.start_date,
            "end_date": self.end_date,
            "is_active": self.is_active,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }

        return data

    def get_image_as_base64(self):
        url = self.image if self.image else DEFAULT_PRODUCT_IMAGE

        with BytesIO() as buffer:
            image = Image.open(url)
            # Convierte la imagen a modo RGB
            image = image.convert("RGB")
            image.save(buffer, format="JPEG")
            return base64.b64encode(buffer.getvalue()).decode()

    def set_previous_inactive(self):
        """ Deactivates all previous campaigns """
        Campaign.objects.all().update(is_active=False)

    def notify_about_new_campaign(self):
        """
        Notify via Email all previous clients
        about the new campaign
        """
        try:
            # Verify if there are sales with an email registered
            mails = Sale.get_clients_email()

            if mails:
                mailer = NewCampaignMailer()
                mail = mailer.create_mail(
                    f'Visitanos en el Bazar {self.name}',
                    'mails/new_campaign.html',
                    self.to_dict(),
                    mails
                )

                if self.image:
                    mail.attach_file(self.image.path, self.image.name)

                thread = threading.Thread(target=mailer.send_mail, args=(mail,))
                thread.start()
        except Exception as e:
            print(f"Ocurrio un error al notificar a los clientes. Error: {e}")

    def save(self, *args, **kwargs):
        """
        Deactivates all previous campaigns
        before saving the new campaign
        and notifies all clients about
        the new campaign via Email
        """
        self.set_previous_inactive()
        super().save(*args, **kwargs)
        self.notify_about_new_campaign()


class Sale(models.Model):
    user_id = models.IntegerField(
        default=0, help_text="ID del usuario que realizó la venta"
    )
    campaign = models.ForeignKey(
        Campaign, on_delete=models.CASCADE, help_text="Producto vendido"
    )
    date = models.DateTimeField(
        auto_now_add=True,
        help_text="Fecha y hora en la que se realizó la venta"
    )
    change = models.DecimalField(
        max_digits=8, decimal_places=2,
        help_text="Cambio dado al cliente"
    )
    payment = models.DecimalField(
        max_digits=8, decimal_places=2,
        help_text="Pago recibido del cliente"
    )
    gain = models.DecimalField(
        max_digits=8, decimal_places=2,
        help_text="Ganancia total de la venta"
    )
    amount = models.DecimalField(
        max_digits=8, decimal_places=2,
        help_text="Monto total de la venta"
    )
    products = models.IntegerField(
        help_text="Cantidad de productos vendidos"
    )
    client_email = models.EmailField(
        null=True, blank=True,
        help_text="Correo electrónico del cliente"
    )

    def __str__(self):
        return (
            f"Venta #{self.id} realizada por usuario #{self.user_id} "
            f"el {self.date}. Ganancia: {self.gain}"
        )

    def get_folio(self):
        folio = str(self.id)
        return "#{:0>3}".format(folio)

    def to_dict(self):
        data = {
            "id": self.id,
            "user_id": self.user_id,
            "date": self.date,
            "change": self.change,
            "payment": self.payment,
            "gain": self.gain,
            "amount": self.amount,
            "products": self.products,
            "items": [
                {
                    "product": sale_item.product.name,
                    "quantity": sale_item.quantity,
                    "price": sale_item.price,
                    "gain": sale_item.gain,
                }
                for sale_item in self.saleitem_set.all()
            ],
        }
        return data

    @classmethod
    def get_sale_by_id(cls, sale_id):
        return cls.objects.get(id=sale_id)

    @classmethod
    def get_clients_email(cls):
        return {
            client.client_email for client
            in cls.objects.all() if client.client_email
        }


class SaleItem(models.Model):
    sale = models.ForeignKey(
        Sale, on_delete=models.CASCADE,
        help_text="Venta a la que pertenece el item"
    )
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE,
        help_text="Producto vendido"
    )
    quantity = models.IntegerField(
        default=0,

point_of_sale/templates/campaign_detail.html
{% extends 'base.html' %}
{% block style %}
    <style>
        .table-wrapper {
            height: 550px; /* Altura fija */
            overflow-y: auto; /* Habilite el desplazamiento vertical */
        }

        .thead-fixed {
            position: sticky;
            top: 0;
            background-color: white;
        }
    </style>
{% endblock %}
{% block content %}

    <!-- Modal: Finalizar Campana -->
    <div class="modal fade" id="modalFinalizarCampana" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="myModalLabel">Finalizar Campana</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Esta seguro de querer dar por finalizada la Campana ?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal" id="btn_end_campaign">Finalizar</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Detalle de campaña #{{ campaign.id }}</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'point_of_sale:index' %}">Inicio</a></li>
                        <li class="breadcrumb-item"><a href="#" onclick="history.back(); return false;">Campañas</a>
                        </li>
                        <li class="breadcrumb-item active">Detalle de campaña</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="card">
                    <img src="data:image/png;base64,{{ campaign.get_image_as_base64 }}" class="card-img-top"
                         alt="{{ campaign.name }}" style="max-height: 550px;">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title">{{ campaign.name }}</h2>
                        <br>
                        <hr>
                        <p class="card-text"><strong>Lugar:</strong> {{ campaign.place }}</p>
                        <p class="card-text"><strong>Direccion:</strong> {{ campaign.address }}</p>
                        <p class="card-text"><strong>Fecha (Inicio):</strong> {{ campaign.start_date }}</p>
                        <p class="card-text"><strong>Fecha (Fin):</strong> {{ campaign.end_date }}</p>
                        {% if campaign.is_active %}
                            <p class="card-text text-success"><strong>Estado:</strong> Activo</p>
                        {% else %}
                            <p class="card-text text-danger"><strong>Estado:</strong> Inactivo</p>
                        {% endif %}
                        <p class="card-text"><strong>Ventas:</strong> {{ campaign.sale_set.count }}</p>
                        <p class="card-text"><strong>Productos (Vendidos):</strong> {{ products_sold_count }}</p>
                        <p class="card-text"><strong>Cover:</strong> ${{ campaign.cover }}</p>
                        <p class="card-text"><strong>Ganancia (Bruta):</strong> ${{ campaign.brute_gain }}</p>
                        <p class="card-text"><strong>Ganancia (Neta):</strong> ${{ campaign.gross_gain }}</p>
                        {% if campaign.is_active %}
                            <button class="btn btn-danger" style="width: 100%;" id="btn_open_modal"><b>FINALIZAR</b></button>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title m-0">Productos Vendidos ( {{ products_sold_count }} )</h5>
                    </div>
                    <div class="card-body">
                        <div class="table-wrapper">
                            <table class="table table-sm" id="dt_table">
                                <thead class="thead-fixed">
                                <tr>
                                    <th scope="col">Producto</th>
                                    <th scope="col">Imagen</th>
                                    <th scope="col">Categoria</th>
                                    <th scope="col">Estado</th>
                                    <th scope="col">Stock</th>
                                    <th scope="col">Precio (Venta)</th>
                                    <th scope="col">Ganancia</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for sale in campaign.sale_set.all %}
                                    {% for sale_item in sale.saleitem_set.all %}
                                        <tr>
                                            <th scope="row">{{ sale_item.product }}</th>
                                            <td>
                                                <img src="data:image/png;base64,{{ sale_item.product.get_image_as_base64 }}"
                                                     width="85px">
                                            </td>
                                            <td>{{ sale_item.product.category }}</td>
                                            <td>
                                                {% if sale_item.product.is_active %}
                                                    <span class="badge badge-success">Activo</span>
                                                {% else %}
                                                    <span class="badge badge-danger">Inactivo</span>
                                                {% endif %}
                                            </td>
                                            <td>{{ sale_item.product.inventory_quantity }}</td>
                                            <td>${{ sale_item.price }}</td>
                                            <td>${{ sale_item.gain }}</td>
                                        </tr>
                                    {% endfor %}
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
    const btn_open_modal = document.querySelector("#btn_open_modal");
    const btn_end_campaign = document.querySelector("#btn_end_campaign");

    btn_open_modal.addEventListener("click", event => {
        $("#modalFinalizarCampana").modal("show");
    });

    btn_end_campaign.addEventListener("click", async event => {
        try {
            let url = "{% url 'point_of_sale:end_campaign' campaign.id %}";
            let response = await fetch(url);
            if (response.ok)
            {
                window.location.reload();
            }
        } catch (error) {
            console.error("Error fetching email suggestions:", error);
        }
    });

    </script>
{% endblock %}

point_of_sale/templates/campaigns.html
{% extends 'base.html' %}
{% block content %}
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Campañas ({{ campaigns.count }})</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'point_of_sale:index' %}">Inicio</a></li>
                        <li class="breadcrumb-item active">Campañas</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title m-0">Tabla de campañas</h5>
                            {#              <a href="{% url 'point_of_sale:new_sale' %}" class="btn btn-primary float-right">Registrar venta</a>#}
                        </div>
                        <div class="card-body">
                            <table class="table" id="dt_table">
                                <thead>
                                <tr>
                                    <th scope="col">Campaña</th>
                                    <th scope="col">Imagen</th>
                                    <th scope="col">Fecha (Inicio)</th>
                                    <th scope="col">Fecha (Fin)</th>
                                    <th scope="col">Ventas</th>
                                    <th scope="col">Cover</th>
                                    <th scope="col">Ganancia (Bruta)</th>
                                    <th scope="col">Ganancia (Neta)</th>
                                    <th scope="col">Estado</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% if campaigns.count > 0 %}
                                    {% for campaign in campaigns %}
                                        <tr>
                                            <th scope="row">
                                                <a href="{% url 'point_of_sale:campaign_detail' campaign.id %}">
                                                    {{ campaign }}
                                                </a>
                                            </th>
                                            <td>
                                                <img src="data:image/png;base64,{{ campaign.get_image_as_base64 }}"
                                                     width="180px">
                                            </td>
                                            <td>{{ campaign.start_date|date:'d/m/Y H:i' }}</td>
                                            <td>{{ campaign.end_date|date:'d/m/Y H:i' }}</td>
                                            <td>{{ campaign.sale_set.count }}</td>
                                            <td>${{ campaign.cover }}</td>
                                            <td>${{ campaign.gain }}</td>
                                            <td>${{ campaign.net_gain }}</td>
                                            <td>
                                                {% if campaign.is_active %}
                                                    <span class="badge badge-success">Activo</span>
                                                {% else %}
                                                    <span class="badge badge-danger">Inactivo</span>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                {% else %}
                                    <tr>
                                        <td colspan="5">
                                            <center>
                                                Aún no hay campaignos registrados.
                                            </center>
                                        </td>
                                    </tr>
                                {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.content -->
{% endblock %}

point_of_sale/templates/categories.html
{% extends 'base.html' %}
{% block content %}
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Categorias ({{ categories.count }})</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'point_of_sale:index' %}">Inicio</a></li>
                        <li class="breadcrumb-item active">Categorias</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title m-0">Tabla de categorias</h5>
                            {#              <a href="{% url 'point_of_sale:new_sale' %}" class="btn btn-primary float-right">Registrar venta</a>#}
                        </div>
                        <div class="card-body">
                            <table class="table table-sm table-striped" id="dt_table">
                                <thead>
                                <tr>
                                    <th scope="col">Categoria</th>
                                    <th scope="col">Estado</th>
                                    <th scope="col">Fecha (Creacion)</th>
                                    <th scope="col">Fecha (Ult. Actualizacion)</th>
                                    <th scope="col">Productos</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% if categories.count > 0 %}
                                    {% for category in categories %}
                                        <tr>
                                            <th scope="row">{{ category }}</th>
                                            <td>
                                                {% if category.is_active %}
                                                    <span class="badge badge-success">Activo</span>
                                                {% else %}
                                                    <span class="badge badge-danger">Inactivo</span>
                                                {% endif %}
                                            </td>
                                            <td>{{ category.created_at }}</td>
                                            <td>{{ category.updated_at }}</td>
                                            <td>
                                                <a href="{% url 'point_of_sale:products_by_category' category_id=category.id %}">
                                                    ({{ category.product_set.count }}) </a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                {% else %}
                                    <tr>
                                        <td colspan="5">
                                            <center>
                                                Aún no hay categorias registradas.
                                            </center>
                                        </td>
                                    </tr>
                                {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.content -->
{% endblock %}

point_of_sale/templates/product_detail.html
{% extends 'base.html' %}

{% block content %}

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Detalle de producto #{{ product.id }}</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'point_of_sale:index' %}">Inicio</a></li>
                        <li class="breadcrumb-item active">Detalle de producto</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="card">
                    <img src="data:image/png;base64,{{ product.get_image_as_base64 }}" class="card-img-top"
                         alt="{{ product.name }}">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title">{{ product.name }}</h2>
                        <br>
                        <hr>
                        <p class="card-text"><strong>Categoría:</strong> {{ product.category }}</p>
                        <p class="card-text"><strong>Precio (Venta):</strong> {{ product.sold_price }}</p>
                        <p class="card-text"><strong>Precio (Compra):</strong> {{ product.buy_price }}</p>
                        <p class="card-text"><strong>Existencias:</strong> {{ product.inventory_quantity }}</p>
                        <p class="card-text"><strong>Talla:</strong> {{ product.size }}</p>
                        <p class="card-text"><strong>Color:</strong> {{ product.color }}</p>
                        {% if product.is_active %}
                            <p class="card-text text-success"><strong>Estado:</strong> Activo</p>
                        {% else %}
                            <p class="card-text text-danger"><strong>Estado:</strong> Inactivo</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}