marimon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        '',
        LoginView.as_view(template_name='registration/login.html'),
        name='login'
    ),
    path('logout/', LogoutView.as_view(), name='logout'),
    path(
        'point_of_sale/',
        include('point_of_sale.urls', namespace='point_of_sale')
    )
]

point_of_sale/urls.py
from django.urls import path
from . import views

app_name = 'point_of_sale'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'sale/<int:sale_id>/',
        views.sale_detail,
        name='sale_detail'
    ),
    path(
        'categories/',
        views.categories,
        name='categories'
    ),
    path(
        'category/<int:category_id>/products/',
        views.products_by_category,
        name='products_by_category'
    ),
    path(
        'products/',
        views.products,
        name='products'
    ),
    path(
        'product/<int:product_id>/',
        views.product_detail,
        name='product_detail'
    ),
    path(
        'new-sale/',
        views.new_sale,
        name='new_sale'
    ),
    path(
        'get-product/<int:product_id>',
        views.get_product,
        name='get_product'
    ),
    path(
        'get_product_suggestions/',
        views.get_product_suggestions,
        name='get_product_suggestions'
    ),
    path(
        'campaigns/',
        views.campaigns,
        name='campaigns'
    ),
    path(
        'campaign/<int:campaign_id>',
        views.campaign_detail,
        name='campaign_detail'
    ),
    path(
        'end_campaign/<int:campaign_id>',
        views.end_campaign,
        name='end_campaign'
    ),
    path(
        'get_client_email_suggestions/',
        views.get_client_email_suggestions,
        name='get_client_email_suggestions'
    ),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Moda Boutique | by marimon</title>
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico'  %}">

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/fontawesome-free/css/all.css' %}">
    <!-- Data Table CSS -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
    <!-- Data Table Responsive CSS -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
    <!-- Data Table Buttons CSS -->
    <link rel="stylesheet"
          href="{% static 'adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'adminlte/css/adminlte.css' %}">
    <!-- Select2 CSS -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/select2/css/select2.css' %}">

    <!-- Custom Style -->
    {% block style %}

    {% endblock %}
    <style>
        .nav-separator {
            margin-right: 1em;
        }

    </style>
</head>
<body class="hold-transition layout-top-nav">
<div class="wrapper">

    <!-- Navbar -->
    {% include 'navbar.html' %}
    <!-- /.navbar -->

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        {% block content %}

        {% endblock %}
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    {% include 'footer.html' %}
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- Data Tables -->
<script src="{% static 'adminlte/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'adminlte/plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'adminlte/plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'adminlte/plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'adminlte/plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'adminlte/plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'adminlte/plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'adminlte/plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'adminlte/plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>

<!-- AdminLTE App -->
<script src="{% static 'adminlte/js/adminlte.min.js' %}"></script>
<!-- Select2 JS -->
<script src="{% static 'adminlte/plugins/select2/js/select2.js' %}"></script>
<script>
    $(document).ready(function () {
        $("#dt_table").DataTable({
            "responsive": true,
            "lengthChange": true, // mostrar el selector de registros por página
            "autoWidth": false,
            "buttons": ["copy", "excel", "pdf", "colvis"],
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
            "order": [] // desactivar el ordenamiento automático
        }).buttons().container().appendTo('#dt_table_wrapper .col-md-6:eq(0)');

        $(".select2").select2();
    });
</script>
</body>
</html>

templates/base_login.html
{% load static %}
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Moda Boutique | by marimon</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/fontawesome-free/css/all.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlte/css/adminlte.css' %}">
     <!-- Custom Style -->
    {% block style %}

    {% endblock %}
</head>
<body class="hold-transition layout-top-nav">
<div class="wrapper">

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    {% block content %}

    {% endblock %}
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
    {% include 'footer.html' %}
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- AdminLTE App -->
<script src="{% static 'adminlte/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'adminlte/js/demo.js' %}"></script>
</body>
</html>

templates/footer.html
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      <strong>MB</strong>
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; {% now 'Y' %} Moda Boutique</strong> | <small>by marimon</small>
  </footer>

templates/navbar.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
  <div class="container">
    <a href="{% url 'point_of_sale:index' %}" class="navbar-brand">
      <img src="{% static 'img/logo.jpeg' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Moda Boutique</span>
    </a>

    <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse order-3" id="navbarCollapse">
      <!-- Left navbar links -->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a href="{% url 'point_of_sale:index' %}" class="nav-link">Inicio</a>
        </li>
        <li class="nav-item">
          <div class="dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" id="catalogo-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Catálogo
            </a>
              <div class="dropdown-menu" aria-labelledby="catalogo-dropdown">
              <a class="dropdown-item" href="{% url 'point_of_sale:categories' %}">
                <i class="fas fa-tags float-right"></i>
                Categorías ({{ category_count }})
              </a>
              <a class="dropdown-item" href="{% url 'point_of_sale:products' %}">
                <i class="fas fa-shopping-bag float-right"></i>
                Productos ({{ product_count }})
              </a>
            </div>
          </div>
        </li>
        <li class="nav-item">
          <a href="{% url 'point_of_sale:campaigns' %}" class="nav-link">Campañas</a>
        </li>
        {% if request.user.is_superuser %}
          <li class="nav-item">
            <a href="{% url 'admin:index' %}" class="nav-link" target="_blank">Admin</a>
          </li>
        {% endif %}
      </ul>

      <!-- Right navbar links -->
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link disabled">
            <i class="fas fa-user-circle"></i> {{ request.user.get_full_name }}
          </a>
        </li>
        <li class="nav-item">
          <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-link nav-link">
              <i class="fas fa-sign-out-alt"></i> Salir
            </button>
          </form>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!-- /.navbar -->